services:
  bean-talk:
    image: ghcr.io/${GITHUB_REPOSITORY:-shepherdwind/bean-talk}:latest
    container_name: bean-talk
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped 